apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: battlefield6

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: battlefield6
      app.kubernetes.io/part-of: battlefield6-site
