apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: battlefield6
  namespace: argocd
spec:
  project: battlefield6
  source:
    repoURL: https://github.com/gateszhangc/battlefield6.git
    targetRevision: main
    path: deploy/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: battlefield6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
