apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: battlefield6-live-tls
  annotations:
    acme.cert-manager.io/http01-override-ingress-name: battlefield6
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  secretName: battlefield6-live-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - battlefield6.lol
    - www.battlefield6.lol
