apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: battlefield6-cloudflare
spec:
  acme:
    email: gateszhang92@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: battlefield6-cloudflare-acme-account
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
