apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: battlefield6

resources:
  - ../../base
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/environment: prod
    includeSelectors: true

images:
  - name: battlefield6
    newName: registry.144.91.77.245.sslip.io/battlefield6
    newTag: 420d436b794829fa627b250a73c34b8b04a03a0f
